### ISSUE TITLE
[BUG] `biocthis::use_bioc_github_action()` creates invalid call to `BiocManager::install`

### ISSUE THREAD

**Issue by FelixErnst** [lcolladotor/biocthis#13]
Hi,

`biocthis::use_bioc_github_action()` creates a GHA config files which contains the following lines:
```
      - name: Set BiocVersion
        run: |
          BiocManager::install(version = "RELEASE_3_11", ask = FALSE)
        shell: Rscript {0}
```

This causes an error when run on GitHub and is not a valid version number as defined in `?BiocManager::install`

<details><summary>SessionInfo</summary>
<pre>
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19041)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
#> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] biocthis_0.99.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.30       magrittr_1.5     usethis_1.6.3    rlang_0.4.8     
#>  [5] stringr_1.4.0    styler_1.3.2     highr_0.8        tools_4.0.2     
#>  [9] xfun_0.18        htmltools_0.5.0  ellipsis_0.3.1   yaml_2.2.1      
#> [13] digest_0.6.26    tibble_3.0.4     lifecycle_0.2.0  crayon_1.3.4    
#> [17] purrr_0.3.4      vctrs_0.3.4      fs_1.5.0         glue_1.4.2      
#> [21] evaluate_0.14    rmarkdown_2.4    stringi_1.5.3    compiler_4.0.2  
#> [25] pillar_1.4.6     backports_1.1.10 pkgconfig_2.0.3
</pre>
</details>

**Comment by lcolladotor** [comment]
Thanks for reporting this issue. This problem should be fixed now.
