### ISSUE TITLE
knitcitations package not available anymore

### ISSUE THREAD

**Issue by milanmlft** [lcolladotor/biocthis#14]
Thanks for the awesome package!

Unfortunately, the __knitcitations__ package was removed from CRAN: https://cran.r-project.org/web/packages/knitcitations/index.html

Is there any good alternative available that could be used as replacement?

**Comment by lcolladotor** [comment]
This is need to me! Let’s see what they respond. Sometimes CRAN removes packages when they fail some automatic test, but can be added back again. 

https://twitter.com/lcolladotor/status/1322165051688714241?s=21

**Comment by lcolladotor** [comment]
https://github.com/cboettig/knitcitations/issues/107 is related

**Comment by lcolladotor** [comment]
I just posted this https://github.com/cboettig/knitcitations/issues/107#issuecomment-719609483

> I think that the issue is with `RefManageR` which is imported by `knitcitations` https://github.com/cboettig/knitcitations/blob/master/DESCRIPTION#L21 but was removed from CRAN https://cran.r-project.org/web/packages/RefManageR/index.html. 
> 
> I see at https://github.com/ropensci/RefManageR/issues/79 that `RefManageR` just changed maintainers and there was a hiccup which will be resolved based on https://github.com/ropensci/RefManageR/issues/79#issuecomment-718599356

So potentially we just need to wait a few days for this issue to be resolved.

**Comment by lcolladotor** [comment]
By the way, this works in the meantime:

```R
## If needed
if (!requireNamespace("remotes", quietly = TRUE))
    install.packages("remotes")

## Temporary for now due to https://github.com/ropensci/RefManageR/issues/79
remotes::install_github(c(
    "ropensci/bibtex",
    "cboettig/knitcitations",
    "ropensci/RefManageR"
))
```

**Comment by lcolladotor** [comment]
I added a temporary fix for this on both RELEASE_3_12 and devel (Bioc 3.12 and 3.13)
