### ISSUE TITLE
Question: BIOCVERSIONNUM environment variable?

### ISSUE THREAD

**Issue by sa-lee** [lcolladotor/biocthis#2]
Hi Leo,

Thanks for this package, I just set up GHA for plyranges and everything seems to work pretty seamlessly!

I was curious how the environment variable gets set for the windows and macos. On a current PR the jobs seems to be unable to install Bioc because the environment variable is empty.

## Context

Provide some context for your bug report or feature request. This could be the:

* link to windows GHA where the step fails: https://github.com/sa-lee/plyranges/runs/690010956?check_suite_focus=true 

Any ideas why this didn't work?

**Comment by sa-lee** [comment]
I think I've worked this out now! But thanks again for this package setting up the actions was very straightforward thanks to `biocthis`!

**Comment by Takkoona** [comment]
I encountered the same problem. Guess BIOCVERSIONNUM is not set on all non-master branch?

**Comment by Takkoona** [comment]
[Here](https://github.com/wuaipinglab/sitePath/commit/9ec2e7ed095b30ee33e852c4dfc25925f7d708ea) is how I solve the issue. But this only applies when it's merged to the master branch while it could very well be one of the release branches. The solution is not generic enough so I hesitate to make a pull request.

**Comment by lcolladotor** [comment]
This will hopefully be clearer thanks to https://github.com/lcolladotor/biocthis/pull/11 by Marcel Ramos
