### ISSUE TITLE
[BUG] RELEASE branch variable should still be upper case

### ISSUE THREAD

**Issue by sa-lee** [lcolladotor/biocthis#3]
On the actions yml file, I think the variable that's set for the biocversion should still be upper case (or converted to upper case so the correct docker instance can be pulled.

## Context

Provide some context for your bug report or feature request. 

I'm moving a bunch of my packages to use your workflow file, and it errored on my release branch here:

https://github.com/sa-lee/fluentGenomics/runs/698333750?check_suite_focus=true#step:2:12

**Comment by lcolladotor** [comment]
Thanks for the info! I'll add this soon =)

**Comment by lcolladotor** [comment]
@Takkoona solved this at https://github.com/lcolladotor/biocthis/pull/4 ^^
