### ISSUE TITLE
[BUG] CSS template for pkgdown website

### ISSUE THREAD

**Issue by kevinrue** [lcolladotor/biocthis#34]
## Context

Caveat: new "non-standard" directory, see #21

https://community-bioc.slack.com/archives/C35G93GJH/p1661497933425919

> Hi, everyone. Does anyone have examples of pretty pkgdown documentation websites for Bioc packages?
> All of my Bioc packages have documentation websites that I create and automatically update thanks to the GHA workflow provided by {biocthis}. However, I think the default UI could be better.
> I am looking for inspirational examples and suggestions (e.g., themes, fonts, etc). An example of a documentation website I find pretty is the pkgdown website: https://pkgdown.r-lib.org/

## Code

https://gist.github.com/kevinrue/4e0de8bc0635009e7e6bc3ddfe7ddaa9

Store those contents in `pkgdown/extra.css`, in the repository of an R/Bioconductor package on GitHub.

## Small reproducible example

- Code: https://github.com/iSEE/iSEEhub
- Result: https://isee.github.io/iSEEhub/

## R session information

Remember to include your full R session information.

```R
options(width = 120)
sessioninfo::session_info()
```

The output of `sessioninfo::session_info()` includes relevant GitHub installation information and other details that are missed by `sessionInfo()`.

**Comment by lcolladotor** [comment]
Thanks for much for this! https://lcolladotor.github.io/biocthis now uses this ^^

I also added a function (`biocthis::use_bioc_pkgdown_css()`) to make it easier to add this css file and now mention it on the new package template.
