### ISSUE TITLE
setup-r should have @v2 instead of master?

### ISSUE THREAD

**Issue by vjcitn** [lcolladotor/biocthis#36]
https://github.com/lcolladotor/biocthis/blob/341ae80706ecc2950e0a50bc36dc7416f2a5d173/inst/templates/check-bioc.yml#L87

I was having some problems with the workflow yaml today:

```
Error: Unable to resolve action `r-lib/actions@master`, unable to find version `master`
```

 Setting @v2 as the version seems to have solved it.  It might be necessary to change the pandoc action version too.

**Comment by bschilder** [comment]
This is due to the recent removal of  `r-lib/actions@master`

https://github.com/r-lib/actions/issues/639

**Comment by lcolladotor** [comment]
Thanks! This was fixed at https://github.com/lcolladotor/biocthis/pull/37 by @zeehio
