### ISSUE TITLE
[BUG] Default RSPM causes workflow to fail.

### ISSUE THREAD

**Issue by boyiguo1** [lcolladotor/biocthis#41]
## Describe the bug

The workflow generated using `biocthis::use_bioc_github_action.R` can fail during the Install Linux system dependencies step due to the default RSPM (https://packagemanager.rstudio.com/cran/__linux__/jammy/latest) is un available right now.

Is it possible to have a more robust source of RSPM as the default?

### Provide a minimally reproducible example (reprex)
Sorry, the workflow is created as a private repo, and hence can not share with you. But I am attaching a screen print or the error page.

<img width="900" alt="Screenshot 2023-05-24 at 10 26 12 AM" src="https://github.com/lcolladotor/biocthis/assets/16565218/794f520b-97c5-46ee-b6ee-3be293a9921e">

Here is a screen print for the default RSPM unavailable.
<img width="839" alt="Screenshot 2023-05-24 at 10 26 40 AM" src="https://github.com/lcolladotor/biocthis/assets/16565218/04cdc01f-0e30-46ef-bd4d-82e13b4f268b">

## Expected behavior

The workflow will complete successfully.

## R Session Information
The workflow is created using `biocthis v1.11.1`

## Additional Context

The default RSPM is specified in this line
https://github.com/lcolladotor/biocthis/blob/8002314df3b9fe69d7954c269d45abff9b3fed66/inst/templates/check-bioc.yml#L55

## Is the package installed via bioconda? 
N/A

**Comment by lmweber** [comment]
Seems the RStudio / Posit package managers are currently still down / unavailable -- I am still getting this error too.

I have an example of the error in this GHA run: https://github.com/lmweber/nnSVG/actions/runs/5123797666/jobs/9215096509

Also a smaller separate issue -- the package manager URL has changed to the new Posit name, from:

```
https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
```

to

```
https://packagemanager.posit.co/cran/__linux__/jammy/latest
```

although both URLs are still supported for now.

**Comment by lmweber** [comment]
Actually I'm not sure this is due to the RSPM, because I still get the same error when I remove RSPM, e.g. in this run: https://github.com/lmweber/nnSVG/actions/runs/5124676591/jobs/9216830473

I'm not sure yet what is causing this.
