### ISSUE TITLE
Future intentions for package

### ISSUE THREAD

**Issue by Kayla-Morrell** [lcolladotor/biocthis#5]
Hello @lcolladotor - Hope you are doing well!

I've been continuing my work on some new functions for the Hubs, one of which would create a skeleton of a package for data submitted to the Hubs. Previously I was working on a branch of `AnnotationHubData` to create a package from scratch, without the use of  `usethis`. Since then, @mtmorgan has directed me to your `biocthis` package as it has some helpful functionality to create a Bioconductor style package. 

I have two forks in my personal GitHub, one of [AnnotationHubData](https://github.com/Kayla-Morrell/AnnotationHubData/tree/biocthisUse) where I've been working on the new functions and one of [biocthis](https://github.com/Kayla-Morrell/biocthis/tree/KaylaEdits) where I've made some slight modifications to `use_bioc_description()` to accommodate AH and EH type packages. 

We were hoping we could discuss with you a bit about what your intentions might be with `biocthis`. We think it would be a great addition to Bioconductor, as it would be useful not only for our Hub purposes but for other developers as well. Let us know what your thoughts are, we would be more than happy to discuss further with you and/or answer any questions you may have.

Best,
Kayla

**Comment by lcolladotor** [comment]
Hi, that’d be awesome! I’m on a camping trip till July 19th and will get
back to you on the 20th

**Comment by lcolladotor** [comment]
Hi Kayla,

With the Bioconductor new package deadline in two days, I think that it might be best to submit this package after the deadline. I could also try to submit it before the deadline and start the conversation on the bioconductor/contributions corresponding issue. 

Which approach do you think would be best?

Best,
Leo

**Comment by Kayla-Morrell** [comment]
Hey Leo, 

Yes, the deadline for new packages to be submitted is tomorrow the 2nd. The deadline for these new packages to be accepted as part of the release is 10/21. If you'll have time to make changes to the packages before this second deadline I say go for it. If not, no big deal and it can just be submitted after the release. Which ever works best for you I'm fine with.

Hope you are doing well,
Kayla

**Comment by lcolladotor** [comment]
Hi Kayla,

I added your new features from your `biocthis` fork at https://github.com/lcolladotor/biocthis/pull/12 and enabled an option for controlling whether to use the Bioconductor Support website or the GitHub repo issues for the BugReports field.

Best,
Leo

**Comment by lcolladotor** [comment]
I'll submit the package shortly to Bioconductor then. I understand now that you would need the package to be available in order to use it at https://github.com/Kayla-Morrell/AnnotationHubData/tree/biocthisUse. Sorry for taking so long to pick this up!

**Comment by lcolladotor** [comment]
Here it is https://github.com/Bioconductor/Contributions/issues/1674 ^^

**Comment by lcolladotor** [comment]
Hi Kayla,

I just wanted to let you know that `biocthis` has now been accepted into Bioconductor ^^ https://github.com/Bioconductor/Contributions/issues/1674#issuecomment-712311699

Best,
Leo
