### ISSUE TITLE
[FR] Add bioc badges for platforms, downloads, build status

### ISSUE THREAD

**Issue by LiNk-NY** [lcolladotor/biocthis#6]
`usethis` does provide one form of badges but we could add more:
https://github.com/r-lib/usethis/blob/master/R/badge.R#L85

**Comment by lcolladotor** [comment]
Aye, that would be great. I keep editing the badge manually for non-software Bioc packages.

**Comment by lcolladotor** [comment]
Hm... what about referring on the docs to https://github.com/GuangchuangYu/badger ? It's already a CRAN package. 

However, it also doesn't support experiment / annotation / workflow packages from what I see at https://github.com/GuangchuangYu/badger/blob/master/R/badge.R#L92-L129

**Comment by lcolladotor** [comment]
I'm going to close this issue as out of scope for now.

If it becomes a priority again, feel free to re-open it.
